// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDOcYcDIdUFOJlEMSWxuCHNmZ7Kh-8m7OY',
    appId: '1:427664053961:web:92522d98f2b36b1c5d5f18',
    messagingSenderId: '427664053961',
    projectId: 'petty-university',
    authDomain: 'petty-university.firebaseapp.com',
    storageBucket: 'petty-university.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCFBl47_zYJW7Y23vcUwDxN436eyPTjzxY',
    appId: '1:427664053961:android:f4304b9a680215c35d5f18',
    messagingSenderId: '427664053961',
    projectId: 'petty-university',
    storageBucket: 'petty-university.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDdEgYqS201Z1ojxY-8DaQs3kFMYTo8Vdw',
    appId: '1:427664053961:ios:4bfa1d3d092e6e665d5f18',
    messagingSenderId: '427664053961',
    projectId: 'petty-university',
    storageBucket: 'petty-university.firebasestorage.app',
    iosBundleId: 'com.example.pettyUniversity',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDdEgYqS201Z1ojxY-8DaQs3kFMYTo8Vdw',
    appId: '1:427664053961:ios:4bfa1d3d092e6e665d5f18',
    messagingSenderId: '427664053961',
    projectId: 'petty-university',
    storageBucket: 'petty-university.firebasestorage.app',
    iosBundleId: 'com.example.pettyUniversity',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDOcYcDIdUFOJlEMSWxuCHNmZ7Kh-8m7OY',
    appId: '1:427664053961:web:bb9f706c3cc002c15d5f18',
    messagingSenderId: '427664053961',
    projectId: 'petty-university',
    authDomain: 'petty-university.firebaseapp.com',
    storageBucket: 'petty-university.firebasestorage.app',
  );
}
